source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.5.1'

gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.3'
gem 'graphql'
gem 'faker'
gem 'acts-as-taggable-on', '~> 6.5.0'
gem 'rack-cors'
gem 'ancestry'
gem 'rails_jwt_auth'
gem 'pundit'
gem 'acts_as_list'
gem 'pg_search'
gem 'set_as_primary'
gem 'active_storage_validations'
gem "google-cloud-storage", "~> 1.11", require: false

gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'pry', '~> 0.12.2'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem "letter_opener"
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'guard-rspec', require: false
end

group :test do
    gem 'simplecov', require: false
    gem 'shoulda-matchers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
