/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { CaseModel } from "./CaseModel"
import { CaseModelSelector } from "./CaseModel.base"
import { RootStoreType } from "./index"


/**
 * AddMemberPayloadBase
 * auto generated base class for the model AddMemberPayloadModel.
 *
 * Autogenerated return type of AddMember
 */
export const AddMemberPayloadModelBase = MSTGQLObject
  .named('AddMemberPayload')
  .props({
    __typename: types.optional(types.literal("AddMemberPayload"), "AddMemberPayload"),
    case: types.maybeNull(MSTGQLRef(types.late(() => CaseModel))),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class AddMemberPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  case(builder?: string | CaseModelSelector | ((selector: CaseModelSelector) => CaseModelSelector)) { return this.__child(`case`, CaseModelSelector, builder) }
}
export function selectFromAddMemberPayload() {
  return new AddMemberPayloadModelSelector()
}

export const addMemberPayloadModelPrimitives = selectFromAddMemberPayload().clientMutationId
