import { Instance } from "mobx-state-tree"
import { AddMemberPayloadModelBase } from "./AddMemberPayloadModel.base"

/* The TypeScript type of an instance of AddMemberPayloadModel */
export interface AddMemberPayloadModelType extends Instance<typeof AddMemberPayloadModel.Type> {}

/* A graphql query fragment builders for AddMemberPayloadModel */
export { selectFromAddMemberPayload, addMemberPayloadModelPrimitives, AddMemberPayloadModelSelector } from "./AddMemberPayloadModel.base"

/**
 * AddMemberPayloadModel
 *
 * Autogenerated return type of AddMember
 */
export const AddMemberPayloadModel = AddMemberPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
