import { Instance } from "mobx-state-tree"
import { AssignCasePayloadModelBase } from "./AssignCasePayloadModel.base"

/* The TypeScript type of an instance of AssignCasePayloadModel */
export interface AssignCasePayloadModelType extends Instance<typeof AssignCasePayloadModel.Type> {}

/* A graphql query fragment builders for AssignCasePayloadModel */
export { selectFromAssignCasePayload, assignCasePayloadModelPrimitives, AssignCasePayloadModelSelector } from "./AssignCasePayloadModel.base"

/**
 * AssignCasePayloadModel
 *
 * Autogenerated return type of AssignCase
 */
export const AssignCasePayloadModel = AssignCasePayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
