/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { CaseModel } from "./CaseModel"
import { CaseModelSelector } from "./CaseModel.base"
import { RootStoreType } from "./index"


/**
 * AssignCasePayloadBase
 * auto generated base class for the model AssignCasePayloadModel.
 *
 * Autogenerated return type of AssignCase
 */
export const AssignCasePayloadModelBase = MSTGQLObject
  .named('AssignCasePayload')
  .props({
    __typename: types.optional(types.literal("AssignCasePayload"), "AssignCasePayload"),
    /** The updated case. */
    case: types.maybeNull(MSTGQLRef(types.late(() => CaseModel))),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class AssignCasePayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  case(builder?: string | CaseModelSelector | ((selector: CaseModelSelector) => CaseModelSelector)) { return this.__child(`case`, CaseModelSelector, builder) }
}
export function selectFromAssignCasePayload() {
  return new AssignCasePayloadModelSelector()
}

export const assignCasePayloadModelPrimitives = selectFromAssignCasePayload().clientMutationId
