import { Instance } from "mobx-state-tree"
import { ChangeAssigneePayloadModelBase } from "./ChangeAssigneePayloadModel.base"

/* The TypeScript type of an instance of ChangeAssigneePayloadModel */
export interface ChangeAssigneePayloadModelType extends Instance<typeof ChangeAssigneePayloadModel.Type> {}

/* A graphql query fragment builders for ChangeAssigneePayloadModel */
export { selectFromChangeAssigneePayload, changeAssigneePayloadModelPrimitives, ChangeAssigneePayloadModelSelector } from "./ChangeAssigneePayloadModel.base"

/**
 * ChangeAssigneePayloadModel
 *
 * Autogenerated return type of ChangeAssignee
 */
export const ChangeAssigneePayloadModel = ChangeAssigneePayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
