import { Instance } from "mobx-state-tree"
import { ChangeStatusPayloadModelBase } from "./ChangeStatusPayloadModel.base"

/* The TypeScript type of an instance of ChangeStatusPayloadModel */
export interface ChangeStatusPayloadModelType extends Instance<typeof ChangeStatusPayloadModel.Type> {}

/* A graphql query fragment builders for ChangeStatusPayloadModel */
export { selectFromChangeStatusPayload, changeStatusPayloadModelPrimitives, ChangeStatusPayloadModelSelector } from "./ChangeStatusPayloadModel.base"

/**
 * ChangeStatusPayloadModel
 *
 * Autogenerated return type of ChangeStatus
 */
export const ChangeStatusPayloadModel = ChangeStatusPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
