/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { CaseModel } from "./CaseModel"
import { CaseModelSelector } from "./CaseModel.base"
import { IndicatorModel } from "./IndicatorModel"
import { IndicatorModelSelector } from "./IndicatorModel.base"
import { TaskModel } from "./TaskModel"
import { TaskModelSelector } from "./TaskModel.base"
import { RootStoreType } from "./index"


/**
 * ChangeDescriptionPayloadBase
 * auto generated base class for the model ChangeDescriptionPayloadModel.
 *
 * Autogenerated return type of ChangeDescription
 */
export const ChangeDescriptionPayloadModelBase = MSTGQLObject
  .named('ChangeDescriptionPayload')
  .props({
    __typename: types.optional(types.literal("ChangeDescriptionPayload"), "ChangeDescriptionPayload"),
    /** The updated case. Is null if you're not updating a case. */
    case: types.maybeNull(MSTGQLRef(types.late(() => CaseModel))),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    /** The updated indicator. Is null if you're not updating a indicator. */
    indicator: types.maybeNull(MSTGQLRef(types.late(() => IndicatorModel))),
    /** The updated task. Is null if you're not updating a task. */
    task: types.maybeNull(MSTGQLRef(types.late(() => TaskModel))),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class ChangeDescriptionPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  case(builder?: string | CaseModelSelector | ((selector: CaseModelSelector) => CaseModelSelector)) { return this.__child(`case`, CaseModelSelector, builder) }
  indicator(builder?: string | IndicatorModelSelector | ((selector: IndicatorModelSelector) => IndicatorModelSelector)) { return this.__child(`indicator`, IndicatorModelSelector, builder) }
  task(builder?: string | TaskModelSelector | ((selector: TaskModelSelector) => TaskModelSelector)) { return this.__child(`task`, TaskModelSelector, builder) }
}
export function selectFromChangeDescriptionPayload() {
  return new ChangeDescriptionPayloadModelSelector()
}

export const changeDescriptionPayloadModelPrimitives = selectFromChangeDescriptionPayload().clientMutationId
