import { Instance } from "mobx-state-tree"
import { ChangePriorityPayloadModelBase } from "./ChangePriorityPayloadModel.base"

/* The TypeScript type of an instance of ChangePriorityPayloadModel */
export interface ChangePriorityPayloadModelType extends Instance<typeof ChangePriorityPayloadModel.Type> {}

/* A graphql query fragment builders for ChangePriorityPayloadModel */
export { selectFromChangePriorityPayload, changePriorityPayloadModelPrimitives, ChangePriorityPayloadModelSelector } from "./ChangePriorityPayloadModel.base"

/**
 * ChangePriorityPayloadModel
 *
 * Autogenerated return type of ChangePriority
 */
export const ChangePriorityPayloadModel = ChangePriorityPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
