import { Instance } from "mobx-state-tree"
import { ChangeDescriptionPayloadModelBase } from "./ChangeDescriptionPayloadModel.base"

/* The TypeScript type of an instance of ChangeDescriptionPayloadModel */
export interface ChangeDescriptionPayloadModelType extends Instance<typeof ChangeDescriptionPayloadModel.Type> {}

/* A graphql query fragment builders for ChangeDescriptionPayloadModel */
export { selectFromChangeDescriptionPayload, changeDescriptionPayloadModelPrimitives, ChangeDescriptionPayloadModelSelector } from "./ChangeDescriptionPayloadModel.base"

/**
 * ChangeDescriptionPayloadModel
 *
 * Autogenerated return type of ChangeDescription
 */
export const ChangeDescriptionPayloadModel = ChangeDescriptionPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
