import { Instance } from "mobx-state-tree"
import { CreatePriorityPayloadModelBase } from "./CreatePriorityPayloadModel.base"

/* The TypeScript type of an instance of CreatePriorityPayloadModel */
export interface CreatePriorityPayloadModelType extends Instance<typeof CreatePriorityPayloadModel.Type> {}

/* A graphql query fragment builders for CreatePriorityPayloadModel */
export { selectFromCreatePriorityPayload, createPriorityPayloadModelPrimitives, CreatePriorityPayloadModelSelector } from "./CreatePriorityPayloadModel.base"

/**
 * CreatePriorityPayloadModel
 *
 * Autogenerated return type of CreatePriority
 */
export const CreatePriorityPayloadModel = CreatePriorityPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
