/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { StatusModel } from "./StatusModel"
import { StatusModelSelector } from "./StatusModel.base"
import { RootStoreType } from "./index"


/**
 * CreateStatusPayloadBase
 * auto generated base class for the model CreateStatusPayloadModel.
 *
 * Autogenerated return type of CreateStatus
 */
export const CreateStatusPayloadModelBase = MSTGQLObject
  .named('CreateStatusPayload')
  .props({
    __typename: types.optional(types.literal("CreateStatusPayload"), "CreateStatusPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    /** The newly created status. */
    status: types.maybeNull(MSTGQLRef(types.late(() => StatusModel))),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class CreateStatusPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  status(builder?: string | StatusModelSelector | ((selector: StatusModelSelector) => StatusModelSelector)) { return this.__child(`status`, StatusModelSelector, builder) }
}
export function selectFromCreateStatusPayload() {
  return new CreateStatusPayloadModelSelector()
}

export const createStatusPayloadModelPrimitives = selectFromCreateStatusPayload().clientMutationId
