/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { CaseModel } from "./CaseModel"
import { CaseModelSelector } from "./CaseModel.base"
import { RootStoreType } from "./index"


/**
 * CreateCasePayloadBase
 * auto generated base class for the model CreateCasePayloadModel.
 *
 * Autogenerated return type of CreateCase
 */
export const CreateCasePayloadModelBase = MSTGQLObject
  .named('CreateCasePayload')
  .props({
    __typename: types.optional(types.literal("CreateCasePayload"), "CreateCasePayload"),
    /** The newly created case. */
    case: types.maybeNull(MSTGQLRef(types.late(() => CaseModel))),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class CreateCasePayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  case(builder?: string | CaseModelSelector | ((selector: CaseModelSelector) => CaseModelSelector)) { return this.__child(`case`, CaseModelSelector, builder) }
}
export function selectFromCreateCasePayload() {
  return new CreateCasePayloadModelSelector()
}

export const createCasePayloadModelPrimitives = selectFromCreateCasePayload().clientMutationId
