import { Instance } from "mobx-state-tree"
import { CreateCasePayloadModelBase } from "./CreateCasePayloadModel.base"

/* The TypeScript type of an instance of CreateCasePayloadModel */
export interface CreateCasePayloadModelType extends Instance<typeof CreateCasePayloadModel.Type> {}

/* A graphql query fragment builders for CreateCasePayloadModel */
export { selectFromCreateCasePayload, createCasePayloadModelPrimitives, CreateCasePayloadModelSelector } from "./CreateCasePayloadModel.base"

/**
 * CreateCasePayloadModel
 *
 * Autogenerated return type of CreateCase
 */
export const CreateCasePayloadModel = CreateCasePayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
