/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, QueryBuilder } from "mst-gql"
import { RootStoreType } from "./index"


/**
 * DeleteCasePayloadBase
 * auto generated base class for the model DeleteCasePayloadModel.
 *
 * Autogenerated return type of DeleteCase
 */
export const DeleteCasePayloadModelBase = MSTGQLObject
  .named('DeleteCasePayload')
  .props({
    __typename: types.optional(types.literal("DeleteCasePayload"), "DeleteCasePayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    id: types.identifier,
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class DeleteCasePayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get id() { return this.__attr(`id`) }
}
export function selectFromDeleteCasePayload() {
  return new DeleteCasePayloadModelSelector()
}

export const deleteCasePayloadModelPrimitives = selectFromDeleteCasePayload().clientMutationId
