import { Instance } from "mobx-state-tree"
import { DeleteCommentPayloadModelBase } from "./DeleteCommentPayloadModel.base"

/* The TypeScript type of an instance of DeleteCommentPayloadModel */
export interface DeleteCommentPayloadModelType extends Instance<typeof DeleteCommentPayloadModel.Type> {}

/* A graphql query fragment builders for DeleteCommentPayloadModel */
export { selectFromDeleteCommentPayload, deleteCommentPayloadModelPrimitives, DeleteCommentPayloadModelSelector } from "./DeleteCommentPayloadModel.base"

/**
 * DeleteCommentPayloadModel
 *
 * Autogenerated return type of DeleteComment
 */
export const DeleteCommentPayloadModel = DeleteCommentPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
