/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, QueryBuilder } from "mst-gql"
import { RootStoreType } from "./index"


/**
 * DeleteCommentPayloadBase
 * auto generated base class for the model DeleteCommentPayloadModel.
 *
 * Autogenerated return type of DeleteComment
 */
export const DeleteCommentPayloadModelBase = MSTGQLObject
  .named('DeleteCommentPayload')
  .props({
    __typename: types.optional(types.literal("DeleteCommentPayload"), "DeleteCommentPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    id: types.identifier,
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class DeleteCommentPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get id() { return this.__attr(`id`) }
}
export function selectFromDeleteCommentPayload() {
  return new DeleteCommentPayloadModelSelector()
}

export const deleteCommentPayloadModelPrimitives = selectFromDeleteCommentPayload().clientMutationId
