/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, QueryBuilder } from "mst-gql"
import { RootStoreType } from "./index"


/**
 * DeleteTaskPayloadBase
 * auto generated base class for the model DeleteTaskPayloadModel.
 *
 * Autogenerated return type of DeleteTask
 */
export const DeleteTaskPayloadModelBase = MSTGQLObject
  .named('DeleteTaskPayload')
  .props({
    __typename: types.optional(types.literal("DeleteTaskPayload"), "DeleteTaskPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    id: types.identifier,
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class DeleteTaskPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get id() { return this.__attr(`id`) }
}
export function selectFromDeleteTaskPayload() {
  return new DeleteTaskPayloadModelSelector()
}

export const deleteTaskPayloadModelPrimitives = selectFromDeleteTaskPayload().clientMutationId
