import { Instance } from "mobx-state-tree"
import { DeletePriorityPayloadModelBase } from "./DeletePriorityPayloadModel.base"

/* The TypeScript type of an instance of DeletePriorityPayloadModel */
export interface DeletePriorityPayloadModelType extends Instance<typeof DeletePriorityPayloadModel.Type> {}

/* A graphql query fragment builders for DeletePriorityPayloadModel */
export { selectFromDeletePriorityPayload, deletePriorityPayloadModelPrimitives, DeletePriorityPayloadModelSelector } from "./DeletePriorityPayloadModel.base"

/**
 * DeletePriorityPayloadModel
 *
 * Autogenerated return type of DeletePriority
 */
export const DeletePriorityPayloadModel = DeletePriorityPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
