/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, QueryBuilder } from "mst-gql"
import { RootStoreType } from "./index"


/**
 * DeleteStatusPayloadBase
 * auto generated base class for the model DeleteStatusPayloadModel.
 *
 * Autogenerated return type of DeleteStatus
 */
export const DeleteStatusPayloadModelBase = MSTGQLObject
  .named('DeleteStatusPayload')
  .props({
    __typename: types.optional(types.literal("DeleteStatusPayload"), "DeleteStatusPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    id: types.identifier,
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class DeleteStatusPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get id() { return this.__attr(`id`) }
}
export function selectFromDeleteStatusPayload() {
  return new DeleteStatusPayloadModelSelector()
}

export const deleteStatusPayloadModelPrimitives = selectFromDeleteStatusPayload().clientMutationId
