import { Instance } from "mobx-state-tree"
import { DeleteTaskPayloadModelBase } from "./DeleteTaskPayloadModel.base"

/* The TypeScript type of an instance of DeleteTaskPayloadModel */
export interface DeleteTaskPayloadModelType extends Instance<typeof DeleteTaskPayloadModel.Type> {}

/* A graphql query fragment builders for DeleteTaskPayloadModel */
export { selectFromDeleteTaskPayload, deleteTaskPayloadModelPrimitives, DeleteTaskPayloadModelSelector } from "./DeleteTaskPayloadModel.base"

/**
 * DeleteTaskPayloadModel
 *
 * Autogenerated return type of DeleteTask
 */
export const DeleteTaskPayloadModel = DeleteTaskPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
