/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, QueryBuilder } from "mst-gql"
import { RootStoreType } from "./index"


/**
 * DeletePriorityPayloadBase
 * auto generated base class for the model DeletePriorityPayloadModel.
 *
 * Autogenerated return type of DeletePriority
 */
export const DeletePriorityPayloadModelBase = MSTGQLObject
  .named('DeletePriorityPayload')
  .props({
    __typename: types.optional(types.literal("DeletePriorityPayload"), "DeletePriorityPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    id: types.identifier,
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class DeletePriorityPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get id() { return this.__attr(`id`) }
}
export function selectFromDeletePriorityPayload() {
  return new DeletePriorityPayloadModelSelector()
}

export const deletePriorityPayloadModelPrimitives = selectFromDeletePriorityPayload().clientMutationId
