import { Instance } from "mobx-state-tree"
import { DeleteStatusPayloadModelBase } from "./DeleteStatusPayloadModel.base"

/* The TypeScript type of an instance of DeleteStatusPayloadModel */
export interface DeleteStatusPayloadModelType extends Instance<typeof DeleteStatusPayloadModel.Type> {}

/* A graphql query fragment builders for DeleteStatusPayloadModel */
export { selectFromDeleteStatusPayload, deleteStatusPayloadModelPrimitives, DeleteStatusPayloadModelSelector } from "./DeleteStatusPayloadModel.base"

/**
 * DeleteStatusPayloadModel
 *
 * Autogenerated return type of DeleteStatus
 */
export const DeleteStatusPayloadModel = DeleteStatusPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
