/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { CaseModel } from "./CaseModel"
import { CaseModelSelector } from "./CaseModel.base"
import { RootStoreType } from "./index"


/**
 * MergeCasePayloadBase
 * auto generated base class for the model MergeCasePayloadModel.
 *
 * Autogenerated return type of MergeCase
 */
export const MergeCasePayloadModelBase = MSTGQLObject
  .named('MergeCasePayload')
  .props({
    __typename: types.optional(types.literal("MergeCasePayload"), "MergeCasePayload"),
    /** The case we just merged. */
    childCase: types.maybeNull(MSTGQLRef(types.late(() => CaseModel))),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    /** The case we merged it into. */
    parentCase: types.maybeNull(MSTGQLRef(types.late(() => CaseModel))),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class MergeCasePayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  childCase(builder?: string | CaseModelSelector | ((selector: CaseModelSelector) => CaseModelSelector)) { return this.__child(`childCase`, CaseModelSelector, builder) }
  parentCase(builder?: string | CaseModelSelector | ((selector: CaseModelSelector) => CaseModelSelector)) { return this.__child(`parentCase`, CaseModelSelector, builder) }
}
export function selectFromMergeCasePayload() {
  return new MergeCasePayloadModelSelector()
}

export const mergeCasePayloadModelPrimitives = selectFromMergeCasePayload().clientMutationId
