import { Instance } from "mobx-state-tree"
import { MergeCasePayloadModelBase } from "./MergeCasePayloadModel.base"

/* The TypeScript type of an instance of MergeCasePayloadModel */
export interface MergeCasePayloadModelType extends Instance<typeof MergeCasePayloadModel.Type> {}

/* A graphql query fragment builders for MergeCasePayloadModel */
export { selectFromMergeCasePayload, mergeCasePayloadModelPrimitives, MergeCasePayloadModelSelector } from "./MergeCasePayloadModel.base"

/**
 * MergeCasePayloadModel
 *
 * Autogenerated return type of MergeCase
 */
export const MergeCasePayloadModel = MergeCasePayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
