/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { PriorityModel } from "./PriorityModel"
import { PriorityModelSelector } from "./PriorityModel.base"
import { RootStoreType } from "./index"


/**
 * RenamePriorityPayloadBase
 * auto generated base class for the model RenamePriorityPayloadModel.
 *
 * Autogenerated return type of RenamePriority
 */
export const RenamePriorityPayloadModelBase = MSTGQLObject
  .named('RenamePriorityPayload')
  .props({
    __typename: types.optional(types.literal("RenamePriorityPayload"), "RenamePriorityPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    /** The updated priority. */
    priority: types.maybeNull(MSTGQLRef(types.late(() => PriorityModel))),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class RenamePriorityPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  priority(builder?: string | PriorityModelSelector | ((selector: PriorityModelSelector) => PriorityModelSelector)) { return this.__child(`priority`, PriorityModelSelector, builder) }
}
export function selectFromRenamePriorityPayload() {
  return new RenamePriorityPayloadModelSelector()
}

export const renamePriorityPayloadModelPrimitives = selectFromRenamePriorityPayload().clientMutationId
