import { Instance } from "mobx-state-tree"
import { RenameTaskPayloadModelBase } from "./RenameTaskPayloadModel.base"

/* The TypeScript type of an instance of RenameTaskPayloadModel */
export interface RenameTaskPayloadModelType extends Instance<typeof RenameTaskPayloadModel.Type> {}

/* A graphql query fragment builders for RenameTaskPayloadModel */
export { selectFromRenameTaskPayload, renameTaskPayloadModelPrimitives, RenameTaskPayloadModelSelector } from "./RenameTaskPayloadModel.base"

/**
 * RenameTaskPayloadModel
 *
 * Autogenerated return type of RenameTask
 */
export const RenameTaskPayloadModel = RenameTaskPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
