import { Instance } from "mobx-state-tree"
import { RenamePriorityPayloadModelBase } from "./RenamePriorityPayloadModel.base"

/* The TypeScript type of an instance of RenamePriorityPayloadModel */
export interface RenamePriorityPayloadModelType extends Instance<typeof RenamePriorityPayloadModel.Type> {}

/* A graphql query fragment builders for RenamePriorityPayloadModel */
export { selectFromRenamePriorityPayload, renamePriorityPayloadModelPrimitives, RenamePriorityPayloadModelSelector } from "./RenamePriorityPayloadModel.base"

/**
 * RenamePriorityPayloadModel
 *
 * Autogenerated return type of RenamePriority
 */
export const RenamePriorityPayloadModel = RenamePriorityPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
