import { Instance } from "mobx-state-tree"
import { RenameStatusPayloadModelBase } from "./RenameStatusPayloadModel.base"

/* The TypeScript type of an instance of RenameStatusPayloadModel */
export interface RenameStatusPayloadModelType extends Instance<typeof RenameStatusPayloadModel.Type> {}

/* A graphql query fragment builders for RenameStatusPayloadModel */
export { selectFromRenameStatusPayload, renameStatusPayloadModelPrimitives, RenameStatusPayloadModelSelector } from "./RenameStatusPayloadModel.base"

/**
 * RenameStatusPayloadModel
 *
 * Autogenerated return type of RenameStatus
 */
export const RenameStatusPayloadModel = RenameStatusPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
