/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { CaseModel } from "./CaseModel"
import { CaseModelSelector } from "./CaseModel.base"
import { RootStoreType } from "./index"


/**
 * RenameCasePayloadBase
 * auto generated base class for the model RenameCasePayloadModel.
 *
 * Autogenerated return type of RenameCase
 */
export const RenameCasePayloadModelBase = MSTGQLObject
  .named('RenameCasePayload')
  .props({
    __typename: types.optional(types.literal("RenameCasePayload"), "RenameCasePayload"),
    /** The updated case. */
    case: types.maybeNull(MSTGQLRef(types.late(() => CaseModel))),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class RenameCasePayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  case(builder?: string | CaseModelSelector | ((selector: CaseModelSelector) => CaseModelSelector)) { return this.__child(`case`, CaseModelSelector, builder) }
}
export function selectFromRenameCasePayload() {
  return new RenameCasePayloadModelSelector()
}

export const renameCasePayloadModelPrimitives = selectFromRenameCasePayload().clientMutationId
