/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { MSTGQLObject, MSTGQLRef, QueryBuilder } from "mst-gql"
import { TaskModel } from "./TaskModel"
import { TaskModelSelector } from "./TaskModel.base"
import { RootStoreType } from "./index"


/**
 * RenameTaskPayloadBase
 * auto generated base class for the model RenameTaskPayloadModel.
 *
 * Autogenerated return type of RenameTask
 */
export const RenameTaskPayloadModelBase = MSTGQLObject
  .named('RenameTaskPayload')
  .props({
    __typename: types.optional(types.literal("RenameTaskPayload"), "RenameTaskPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.maybeNull(types.string),
    /** The updated task. */
    task: types.maybeNull(MSTGQLRef(types.late(() => TaskModel))),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class RenameTaskPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  task(builder?: string | TaskModelSelector | ((selector: TaskModelSelector) => TaskModelSelector)) { return this.__child(`task`, TaskModelSelector, builder) }
}
export function selectFromRenameTaskPayload() {
  return new RenameTaskPayloadModelSelector()
}

export const renameTaskPayloadModelPrimitives = selectFromRenameTaskPayload().clientMutationId
