import { Instance } from "mobx-state-tree"
import { RenameCasePayloadModelBase } from "./RenameCasePayloadModel.base"

/* The TypeScript type of an instance of RenameCasePayloadModel */
export interface RenameCasePayloadModelType extends Instance<typeof RenameCasePayloadModel.Type> {}

/* A graphql query fragment builders for RenameCasePayloadModel */
export { selectFromRenameCasePayload, renameCasePayloadModelPrimitives, RenameCasePayloadModelSelector } from "./RenameCasePayloadModel.base"

/**
 * RenameCasePayloadModel
 *
 * Autogenerated return type of RenameCase
 */
export const RenameCasePayloadModel = RenameCasePayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
