const paths = {
  ROOT_PATH: "/",
  CASES_PATH: "/cases"
};

const ADD_TAGS = "ADD_TAGS";
const REMOVE_TAGS = "REMOVE_TAGS";
const CHANGE_STATUS = "CHANGE_STATUS";
const CHANGE_PRIORITY = "CHANGE_PRIORITY";

export { paths, ADD_TAGS, REMOVE_TAGS, CHANGE_STATUS, CHANGE_PRIORITY };
