name: Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Deploy to GAE
      run: |
        cd backend
        gcloud config set project tp-landing-page-video
        gcloud app deploy --quiet
         
