name: Ruby

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Install dependencies
      run: |
        sudo apt-get install postgresql-client libpq5 libpq-dev
        cd backend
        gem install bundler
        bundle update --bundler
        bundle install --jobs 4 --retry 3
    - name: Run gcloud info
      run: gcloud info
         
